[tool.poetry]
name = "maia"
version = "0.1.0"
description = ""
authors = ["Alan Red <alaredmaiar@proton.me>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
faiss-cpu = "^1.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
